export const incidentDataset = {
  generatedAt: "2026-10-07T13:40:00Z",
  environment: "production",
  region: "us-east-1",
  incidents: [
    {
      id: "INC-1842",
      title: "Checkout API elevated 5xx errors",
      status: "investigating",
      severity: "SEV-2",
      startedAt: "2026-10-07T12:14:00Z",
      service: "checkout-api",
      summary:
        "POST /v1/checkout began failing shortly after the 12:08 UTC deploy. Customers cannot complete payment.",
    },
  ],
  deployments: [
    {
      service: "checkout-api",
      version: "2.4.1",
      deployedAt: "2026-10-07T12:08:12Z",
      deployedBy: "ci-bot",
      change:
        "Lowered PAYMENT_GATEWAY_TIMEOUT_MS from 10000 to 2000 and enabled checkout_fast_timeout.",
      status: "success",
    },
    {
      service: "checkout-api",
      version: "2.4.0",
      deployedAt: "2026-10-06T18:22:00Z",
      deployedBy: "ci-bot",
      change: "Routine dependency updates. No checkout timeout changes.",
      status: "success",
    },
    {
      service: "catalog-api",
      version: "1.19.3",
      deployedAt: "2026-10-07T09:41:00Z",
      deployedBy: "ci-bot",
      change: "Add search filter for brand.",
      status: "success",
    },
  ],
  configChanges: [
    {
      at: "2026-10-07T12:07:50Z",
      key: "PAYMENT_GATEWAY_TIMEOUT_MS",
      previousValue: "10000",
      newValue: "2000",
      service: "checkout-api",
    },
    {
      at: "2026-10-07T12:07:50Z",
      key: "checkout_fast_timeout",
      previousValue: "false",
      newValue: "true",
      service: "checkout-api",
    },
  ],
  logs: [
    {
      timestamp: "2026-10-07T12:14:08Z",
      service: "checkout-api",
      level: "ERROR",
      requestId: "req-7f21",
      message:
        "PaymentGatewayTimeoutError: POST https://pay.internal/charge exceeded 2000ms (elapsed=2784ms)",
      route: "POST /v1/checkout",
    },
    {
      timestamp: "2026-10-07T12:14:19Z",
      service: "checkout-api",
      level: "ERROR",
      requestId: "req-7f44",
      message:
        "PaymentGatewayTimeoutError: POST https://pay.internal/charge exceeded 2000ms (elapsed=2611ms)",
      route: "POST /v1/checkout",
    },
    {
      timestamp: "2026-10-07T12:18:41Z",
      service: "checkout-api",
      level: "ERROR",
      requestId: "req-8120",
      message:
        "CheckoutFailed: could not capture payment for cart cart_9aa1 because payment-gateway timed out",
      route: "POST /v1/checkout",
    },
    {
      timestamp: "2026-10-07T12:21:03Z",
      service: "payment-gateway",
      level: "WARN",
      requestId: "pay-4412",
      message: "Upstream processor latency elevated (p95=2840ms, threshold=2500ms)",
      route: "POST /charge",
    },
    {
      timestamp: "2026-10-07T12:10:12Z",
      service: "catalog-api",
      level: "INFO",
      requestId: "cat-2201",
      message: "GET /v1/products completed in 84ms",
      route: "GET /v1/products",
    },
    {
      timestamp: "2026-10-07T11:58:00Z",
      service: "auth-service",
      level: "INFO",
      requestId: "auth-0199",
      message: "Token refresh succeeded",
      route: "POST /oauth/token",
    },
  ],
  metrics: [
    {
      service: "checkout-api",
      window: "2026-10-07T11:00:00Z/2026-10-07T12:00:00Z",
      errorRate: "1.2%",
      p95LatencyMs: 640,
      notes: "Healthy baseline before deploy.",
    },
    {
      service: "checkout-api",
      window: "2026-10-07T12:14:00Z/2026-10-07T13:30:00Z",
      errorRate: "41%",
      p95LatencyMs: 3120,
      notes: "Error spike begins 6 minutes after 2.4.1 deploy. Almost all 5xx are payment timeouts.",
    },
    {
      service: "payment-gateway",
      window: "2026-10-07T12:14:00Z/2026-10-07T13:30:00Z",
      errorRate: "0.4%",
      p95LatencyMs: 2840,
      notes: "Gateway is up, but slower than the new 2000ms checkout timeout.",
    },
    {
      service: "catalog-api",
      window: "2026-10-07T12:14:00Z/2026-10-07T13:30:00Z",
      errorRate: "0.1%",
      p95LatencyMs: 110,
      notes: "Healthy.",
    },
    {
      service: "inventory-api",
      window: "2026-10-07T12:14:00Z/2026-10-07T13:30:00Z",
      errorRate: "0.2%",
      p95LatencyMs: 95,
      notes: "Healthy.",
    },
    {
      service: "checkout-db",
      window: "2026-10-07T12:14:00Z/2026-10-07T13:30:00Z",
      errorRate: "0%",
      p95LatencyMs: 18,
      notes: "Postgres connections and query latency are normal.",
    },
  ],
  serviceHealth: [
    { service: "checkout-api", status: "degraded" },
    { service: "payment-gateway", status: "degraded-latency" },
    { service: "catalog-api", status: "healthy" },
    { service: "inventory-api", status: "healthy" },
    { service: "auth-service", status: "healthy" },
    { service: "checkout-db", status: "healthy" },
  ],
  notes: [
    "Analytics TLS certificate analytics.internal expires in 6 days. Unrelated to checkout failures.",
    "No recent schema migrations on checkout-db.",
    "Redis cache hit rate for checkout sessions is 94% and unchanged.",
  ],
};
